---
ohmyzsh_user:
  - root
  - caynev
ohmyzsh_custom_plugins: true
ohmyzsh_plugin_urls:
  - https://github.com/zsh-users/zsh-autosuggestions.git
  - https://github.com/zsh-users/zsh-syntax-highlighting.git
ohmyzsh_plugin_names:
  - zsh-autosuggestions
  - zsh-syntax-highlighting
ZSH_THEME: agnoster
CASE_SENSITIVE: true
PLUGINS: common-aliases colored-man-pages zsh-syntax-highlighting zsh-autosuggestions vi-mode
