---
vim_user:
  - root
  - caynev
vim_custom_plugins: true
vim_plugin_names:
  - vim-airline
  - nerdtree
  - nord-vim
  - vim-airline-themes
  - vim-yaml
vim_plugin_urls:
  - https://github.com/vim-airline/vim-airline.git
  - https://github.com/preservim/nerdtree.git
  - https://github.com/arcticicestudio/nord-vim.git
  - https://github.com/vim-airline/vim-airline-themes.git
  - https://github.com/stephpy/vim-yaml.git
VIMRC_CONTENT: |
  set number
  set mouse=a
  let g:floaterm_keymap_toggle = '<F12>'
  let g:floaterm_width = 0.9
  let g:floaterm_height = 0.9

  let g:airline_theme='<theme>'
  syntax on
  set t_Co=256
  set cursorline
  silent! colorscheme nord
  let g:airline_theme='nord'
  let g:airline_powerline_fonts=1

  if exists('+termguicolors')
    let &t_8f = "\<Esc>[38;2;%lu;%lu;%lum"
    let &t_8b = "\<Esc>[48;2;%lu;%lu;%lum"
    set termguicolors
  endif

  nnoremap <leader>n :NERDTreeFocus<CR>
  nnoremap <C-n> :NERDTreeToggle<CR>
  nnoremap <C-f> :NERDTreeFind<CR>
