---
- name: Import provisioning.yml
  ansible.builtin.import_playbook: provisioning.yml
  tags: 
  - provisioning

- name: Import configuration.yml
  ansible.builtin.import_playbook: configuration.yml
  tags:
  - configuration 
